baseURL = "/"
languageCode = "en-us"
title = "Kuruvi App"
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[[menu.main]]
    name = "Demo"
    url = "/galleries/"
    weight = 3

[[menu.main]]
    name = "Github"
    url = "https://github.com/Yokeshthirumoorthi/kuruvi"
    weight = 4
    
[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Read The Docs'
  homepage_intro = 'Kuruvi is a smart photo management app.'
  # homepage_image = '/images/terminal.gif'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Kuruvi App documentation site built with Hugo."
    meta_og_title = "Kuruvi App Theme"
    meta_og_type = "website"
    meta_og_url = "https://kuruvidocs.netlify.com"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-whisper-theme/master/images/tn.png"
    meta_og_description = "Kuruvi App documentation site built with Hugo."
    meta_twitter_card = "summary"

  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard  = "/images/logo.svg"
